version: "3"
services:
  springboot:
    image: visureddy247/spring-boot-mongo:VERSION
    environment:
    - MONGO_DB_HOSTNAME=mongo
    ports:
    - 8080:8080
    networks:
    - reddy  
      deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
   
  mongo:
    image: mongo
    volumes:
    - visudb:/data/db
    networks:
    - reddy
    
volumes:
  visudb:
networks:
  reddy:
  
